name: Backup and Restore DynamoDB Tables
on:
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - id: backup_step
        name: Run backup script
        run: ./scripts/backup.sh

      - name: Notify completion
        run: echo "Backup step completed successfully."

      - name: List backups
        run: ./scripts/list_backups.sh
        if: ${{ steps.backup_step.outcome == 'success' }}